services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes

  api:
    build: .
    ports:
      - "8000:8000"
    env_file: /opt/improv-today/improv-today-backend.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    env_file: /opt/improv-today/improv-today-backend.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  beat:
    build: .
    command: celery -A celery_app beat --loglevel=info
    env_file: /opt/improv-today/improv-today-backend.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped


