"""Add enhanced state management with session state and history tracking

Revision ID: 20250917
Revises: 20250916b
Create Date: 2025-09-16 03:13:24.818639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250917'
down_revision: Union[str, None] = '20250916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ava_state', sa.Column('numeric_value', sa.Float(), nullable=True))
    op.add_column('ava_state', sa.Column('trend', sa.String(length=20), nullable=True))
    op.add_column('ava_state', sa.Column('change_reason', sa.Text(), nullable=True))
    op.add_column('ava_state', sa.Column('last_event_id', sa.String(), nullable=True))
    op.add_column('ava_state', sa.Column('min_value', sa.Float(), nullable=True))
    op.add_column('ava_state', sa.Column('max_value', sa.Float(), nullable=True))
    op.add_column('ava_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ava_state', 'created_at')
    op.drop_column('ava_state', 'max_value')
    op.drop_column('ava_state', 'min_value')
    op.drop_column('ava_state', 'last_event_id')
    op.drop_column('ava_state', 'change_reason')
    op.drop_column('ava_state', 'trend')
    op.drop_column('ava_state', 'numeric_value')
    # ### end Alembic commands ###
