"""create_ava_state_table

Revision ID: 20250818
Revises: 57d6fcee68c8
Create Date: 2025-09-07 13:47:05.206376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250818'
down_revision: Union[str, None] = '57d6fcee68c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ava_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('trait_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_ava_state_state_id'), 'ava_state', ['state_id'], unique=False)
    op.create_index(op.f('ix_ava_state_trait_name'), 'ava_state', ['trait_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ava_state_trait_name'), table_name='ava_state')
    op.drop_index(op.f('ix_ava_state_state_id'), table_name='ava_state')
    op.drop_table('ava_state')
    # ### end Alembic commands ###
