"""Add consciousness response fields to global events

Revision ID: 20250916b
Revises: 20250916
Create Date: 2025-09-16 02:22:28.008449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250916b'
down_revision: Union[str, None] = '20250916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_events', sa.Column('emotional_reaction', sa.Text(), nullable=True, comment="Ava's emotional reaction to this event"))
    op.add_column('global_events', sa.Column('chosen_action', sa.Text(), nullable=True, comment='Action Ava chose in response to this event'))
    op.add_column('global_events', sa.Column('internal_thoughts', sa.Text(), nullable=True, comment="Ava's internal thoughts about this event"))
    op.add_column('global_events', sa.Column('consciousness_raw_response', sa.Text(), nullable=True, comment='Raw LLM response for debugging'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_events', 'consciousness_raw_response')
    op.drop_column('global_events', 'internal_thoughts')
    op.drop_column('global_events', 'chosen_action')
    op.drop_column('global_events', 'emotional_reaction')
    # ### end Alembic commands ###
