"""update_conversations_table_for_session_tracking

Revision ID: 20250919
Revises: 20250918
Create Date: 2025-09-26 23:46:28.315242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250919'
down_revision: Union[str, None] = '20250918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to conversations table
    op.add_column('conversations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('personality', sa.String(), nullable=True))

    # Modify existing columns
    op.alter_column('conversations', 'id', type_=sa.String(), existing_type=sa.Integer())
    op.alter_column('conversations', 'user_id', type_=sa.String(), existing_type=sa.Integer())

    # Create indexes
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)

    # Set default values for existing records
    op.execute("UPDATE conversations SET status = 'active' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')

    # Revert column types
    op.alter_column('conversations', 'user_id', type_=sa.Integer(), existing_type=sa.String())
    op.alter_column('conversations', 'id', type_=sa.Integer(), existing_type=sa.String())

    # Drop new columns
    op.drop_column('conversations', 'personality')
    op.drop_column('conversations', 'status')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###
